
package ru.curs.showcase.test.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ShowcaseExternals", targetNamespace = "http://server.app.showcase.curs.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ShowcaseExternals {


    /**
     * 
     * @param procName
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "handle", targetNamespace = "http://server.app.showcase.curs.ru/", className = "ru.curs.showcase.test.ws.Handle")
    @ResponseWrapper(localName = "handleResponse", targetNamespace = "http://server.app.showcase.curs.ru/", className = "ru.curs.showcase.test.ws.HandleResponse")
    @Action(input = "http://server.app.showcase.curs.ru/ShowcaseExternals/handleRequest", output = "http://server.app.showcase.curs.ru/ShowcaseExternals/handleResponse")
    public String handle(
        @WebParam(name = "request", targetNamespace = "")
        String request,
        @WebParam(name = "procName", targetNamespace = "")
        String procName);

}
