//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.23 at 06:03:15 PM MSK 
//


package ru.curs.showcase.app.server.ws;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.curs.showcase.app.server.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.curs.showcase.app.server.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Datapanel }
     * 
     */
    public Datapanel createDatapanel() {
        return new Datapanel();
    }

    /**
     * Create an instance of {@link RequestXML }
     * 
     */
    public RequestXML createRequestXML() {
        return new RequestXML();
    }

    /**
     * Create an instance of {@link Element }
     * 
     */
    public Element createElement() {
        return new Element();
    }

    /**
     * Create an instance of {@link Datapanel.Tab }
     * 
     */
    public Datapanel.Tab createDatapanelTab() {
        return new Datapanel.Tab();
    }

    /**
     * Create an instance of {@link ResponseXML }
     * 
     */
    public ResponseXML createResponseXML() {
        return new ResponseXML();
    }

    /**
     * Create an instance of {@link Tr }
     * 
     */
    public Tr createTr() {
        return new Tr();
    }

    /**
     * Create an instance of {@link Td }
     * 
     */
    public Td createTd() {
        return new Td();
    }

    /**
     * Create an instance of {@link Context }
     * 
     */
    public Context createContext() {
        return new Context();
    }

    /**
     * Create an instance of {@link RequestXML.Command }
     * 
     */
    public RequestXML.Command createRequestXMLCommand() {
        return new RequestXML.Command();
    }

}
