//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.23 at 06:03:15 PM MSK 
//


package ru.curs.showcase.app.server.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}datapanel"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datapanel"
})
@XmlRootElement(name = "responseXML")
public class ResponseXML {

    @XmlElement(required = true)
    protected Datapanel datapanel;

    /**
     * Gets the value of the datapanel property.
     * 
     * @return
     *     possible object is
     *     {@link Datapanel }
     *     
     */
    public Datapanel getDatapanel() {
        return datapanel;
    }

    /**
     * Sets the value of the datapanel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Datapanel }
     *     
     */
    public void setDatapanel(Datapanel value) {
        this.datapanel = value;
    }

}
