//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.23 at 04:34:54 PM MSK 
//


package ru.curs.showcase.app.server.ws;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeProc.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="typeProc">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SAVE"/>
 *     &lt;enumeration value="SUBMISSION"/>
 *     &lt;enumeration value="DOWNLOAD"/>
 *     &lt;enumeration value="UPLOAD"/>
 *     &lt;enumeration value="METADATA"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "typeProc")
@XmlEnum
public enum TypeProc {

    SAVE,
    SUBMISSION,
    DOWNLOAD,
    UPLOAD,
    METADATA;

    public String value() {
        return name();
    }

    public static TypeProc fromValue(String v) {
        return valueOf(v);
    }

}
